webui/instructor/urls.py
from django.urls import path

from . import views

app_name = 'instructor'
urlpatterns = [
    path('', views.index, name='index'),

    path('students', views.studentlist, name='studentlist'),
    path('studentgroup', views.studentgroup, name='studentgroup'),
    path('studentgroup/<int:studentgroup_id>', views.studentgroupdetails, name='studentgroupdetails'),
    path('student/<int:student_id>', views.studentdetails, name='studentdetails'),
    path('newstudent', views.newstudent, name='newstudent'),
    path('studentgroupedit', views.studentgroupedit, name='studentgroupedit'),
    path('studentedit', views.studentedit, name='studentedit'),

    path('student/submission/<int:submission_id>', views.submissiondetails, name='submissiondetails'),

    path('assignments', views.assignmentlist, name='assignmentlist'),
    path('assignment', views.assignment, name='assignment'),
    path('assignmentedit', views.assignmentedit, name='assignmentedit'),
    path('assignment/<int:assignment_id>', views.assignmentdetails, name='assignmentdetails'),

    path('assignmentenvironmentedit', views.assignmentenvironmentedit, name='assignmentenvironmentedit'),
    path('assignmentenvironmentclear', views.assignmentenvironmentclear, name='assignmentenvironmentclear'),

    path('assignmentitem', views.assignmentitem, name='assignmentitem'),
    path('assignmentitemedit', views.assignmentitemedit, name='assignmentitemedit'),
    path('assignmentitemdetails/<int:assignmentitem_id>', views.assignmentitemdetails, name='assignmentitemdetails'),
    path('environmentinstancedatagen', views.datagenstart, name='environmentinstancedatagen'),

    path('environmentinstance', views.environmentinstance, name='environmentinstance'),
    path('environmentinstanceedit', views.environmentinstanceedit, name='environmentinstanceedit'),

    path('grading', views.gradingoverview, name='gradingoverview'),
    path('gradingprocess', views.gradingprocess, name='gradingprocess'),
    path('grading/<int:gradingprocess_id>', views.gradingdetails, name='gradingdetails'),
    path('gradingitem', views.gradingitem, name='gradingitem'),
    path('gradingstart', views.gradingstart, name='gradingstart'),
    path('gradingitemdetails/<int:gradingprocess_id>/<int:assignmentitem_id>', views.gradingitemdetails, name='gradingitemdetails'),

    # api endpoints
    path('api_updategradingstatus', views.update_gradingstatus.as_view(), name='api_updategradingstatus'),
    path('api_getenvironmentinstances/<int:assignmentitem_id>', views.get_environmentinstances.as_view(), name='api_getenvironmentinstances'),
    path('api_getstudentsubmissions/<int:assignmentitem_id>', views.get_studentsubmissions.as_view(), name='api_getstudentsubmissions'),
    path('api_updatestudentsubmissionitem', views.update_studentsubmissionitem.as_view(), name='api_updatestudentsubmissionitem'),
    path('api_updateenvironmentinstance', views.update_environmentinstance.as_view(), name='api_updateenvironmentinstance'),
    path('api_updatestudentsubmissionquery', views.update_studentsubmissionquery.as_view(), name='api_updatestudentsubmissionquery'),


    # bulk import actions
    path('studentimport', views.import_students_togroup, name='studentimport'),
] 

webui/sqlgrader/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import rootRedirect, reportRedirect

urlpatterns = [
    path('instructor/', include('instructor.urls')),
    path('admin/', admin.site.urls),
    # report builder
    path('report_builder/', include('report_builder.urls')),
    path('reports/', reportRedirect),
    # root redirect to instructor
    path('', rootRedirect),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICURL_ROOT)

webui/instructor/forms/__initi__.py
from .assignments import *

webui/instructor/views/apis.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from ..models import GradingProcess, GradingAssignment, GradingContainer, Assignment, AssignmentItem, AssignmentEnvironment, StudentSubmissionItem, EnvironmentInstance, StudentSubmissionItemGrade

from ..serializers import GradingAssignmentSerializer, EnvironmentInstanceSerializer, SubmissionItemSerializer

class get_environmentinstances(APIView):
    permission_classes = (IsAuthenticated, )

    def get(self, request, assignmentitem_id):
        try:
            assignment_item = AssignmentItem.objects.get(pk=assignmentitem_id)
            environment_instances =  EnvironmentInstanceSerializer(EnvironmentInstance.objects.filter(item=assignment_item), many=True)
        except AssignmentItem.DoesNotExist:
            raise Http404("assignment item does not exist")
        return Response(environment_instances.data)

class get_studentsubmissions(APIView):
    permission_classes = (IsAuthenticated, )

    def get(self, request, assignmentitem_id):
        try:
            student_submissions = SubmissionItemSerializer(StudentSubmissionItem.objects.filter(assignment_item_id=assignmentitem_id), many=True)
        except AssignmentItem.DoesNotExist:
            raise Http404("assignment item does not exist")
        return Response(student_submissions.data)

class update_gradingstatus(APIView):
    permission_classes = (IsAuthenticated, )

    def post(self, request):
        # api endpoint to update grading status, returns 200
        try:
            grading_process_id = request.data['grading_process_id']
            grading_process = GradingProcess.objects.get(pk=grading_process_id)
        except GradingProcess.DoesNotExist:
            raise Http404("grading process does not exist")

        # if status_message is not empty, update grading status
        if 'status_message' in request.data and request.data['status_message'] != '':
            grading_process.gradingstatusupdate(request.data['status_message'])
        # if log_update is not empty, add to grading_process log
        if 'log_update' in request.data and request.data['log_update'] != '':
            grading_process.gradinglogupdate(request.data['log_update'])

        return HttpResponse(status=200)

# update the student submission based on individual environment grades
class update_studentsubmissionquery(APIView):
    permission_classes = (IsAuthenticated, )

    def post(self, request):
        # api endpoint to update student submission, returns 200
        # request.data should contain: assignment_item_id

        try:
            assignment_item = AssignmentItem.objects.get(pk=request.data['assignment_item_id'])
        except AssignmentItem.DoesNotExist:
            raise Http404("assignment item does not exist")

        # get all student submissions for this assignment item
        student_submissions = StudentSubmissionItem.objects.filter(assignment_item=assignment_item)
        
        for student_submission in student_submissions:
            item_grades = StudentSubmissionItemGrade.objects.filter(student_submission_item=student_submission)
            total_points_possible = 0.0
            total_points_earned = 0.0
            for item_grade in item_grades:
                total_points_possible += item_grade.points_possible
                total_points_earned += item_grade.points_earned
            if total_points_possible > 0:
                student_submission.score_primary = total_points_earned / total_points_possible
            else:
                student_submission.score_primary = 0.0
            student_submission.save()

        return HttpResponse(status=200)


# update student submission items - either root item for schema or individual query environments
class update_studentsubmissionitem(APIView):
    permission_classes = (IsAuthenticated, )

    def post(self, request):
        # api endpoint to update student submission item - grading_log, score_primary, score_secondary, points_possible, points_earned
        try:
            student_submission_item_id = request.data['student_submission_item_id']
            student_submission_item = StudentSubmissionItem.objects.get(pk=student_submission_item_id)
        except StudentSubmissionItem.DoesNotExist:
            raise Http404("student submission item does not exist")
        

        # if grading_log is not empty, add to grading_log
        if 'grading_log' in request.data and request.data['grading_log'] != '':
            student_submission_item.gradinglogupdate(request.data['grading_log'])

        if 'score_primary' in request.data and request.data['score_primary'] != '':
            student_submission_item.score_primary = request.data['score_primary']
            student_submission_item.save()
        if 'score_secondary' in request.data and request.data['score_secondary'] != '':
            student_submission_item.score_secondary = request.data['score_secondary']
            student_submission_item.save()


        if 'environment_instance_id' in request.data:
            environment_instance = EnvironmentInstance.objects.get(pk=request.data['environment_instance_id'])
            # create a new StudentSubmissionItemGrade - points_possible, points_earned - based on the query grade info
            new_grade = StudentSubmissionItemGrade(student_submission_item=student_submission_item, environment_instance=environment_instance, points_possible=environment_instance.points_possible, points_earned= float(environment_instance.points_possible) * ( float(request.data['points_earned'])) /float(request.data['points_possible']) )
            new_grade.save()
        else:
            environment_instance = EnvironmentInstance.objects.get(item=student_submission_item.assignment_item)
            # create a new StudentSubmissionItemGrade - based on the schema score_primary
            new_grade = StudentSubmissionItemGrade(student_submission_item=student_submission_item, environment_instance=environment_instance, points_possible=environment_instance.points_possible, points_earned= float(request.data['score_primary']) )
            new_grade.save()

        return HttpResponse(status=200)

# mark an environment instance for datagen completion
class update_environmentinstance(APIView):
    permission_classes = (IsAuthenticated, )

    def post(self, request):
        print(request)
        #api endpoint to update environment instance - has_datagen and datagen_status
        try:
            environment_instance_id = request.data['environment_instance_id']
            environment_instance = EnvironmentInstance.objects.get(pk=environment_instance_id)
        except EnvironmentInstance.DoesNotExist:
            raise Http404("environment instance does not exist")
        
        if 'has_datagen' in request.data:
            environment_instance.has_datagen = request.data['has_datagen']
        if 'datagen_status' in request.data and request.data['datagen_status'] != '':
            environment_instance.datagen_status = request.data['datagen_status']

        environment_instance.save()

        return HttpResponse(status=200)

webui/instructor/views/grading.py
from configparser import Error
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User

import requests, json
from rest_framework.authtoken.models import Token

from ..models import GradingProcess, GradingAssignment, GradingContainer, Assignment, AssignmentItem, AssignmentEnvironment, StudentSubmissionItem, StudentSubmissionItemGrade, EnvironmentInstance
from ..tables import gradingtables
from ..serializers import GradingAssignmentSerializer, EnvironmentInstanceSerializer, SubmissionItemSerializer

APIURL = "http://host.docker.internal:5000/"

def gradingoverview(request):
    full_grading_list = GradingProcess.objects.all()
    assignments_tograde = Assignment.objects.filter(is_active=True).values()
    context = {
        'full_grading_list': full_grading_list,
        'assignments_tograde': assignments_tograde,
    }
    return render(request, 'instructor/gradingoverview.html', context)

# creates a new grading process
# form element default_assignment
def gradingprocess(request):
    try:
        new_gradingprocess = GradingProcess.objects.create(assignment=Assignment.objects.get(id=request.POST['default_assignment']))
        new_gradingprocess.save()
        for new_assignment_item in AssignmentItem.objects.filter(assignment__is_active=True):
            new_gradingassignment = GradingAssignment.objects.create(assignment_item=new_assignment_item, grading_process=new_gradingprocess)
            new_gradingassignment.save()
    except:
        raise Http404("Error creating grading process")
    return HttpResponseRedirect(reverse('instructor:gradingoverview'))


# grading process detail view
def gradingdetails(request, gradingprocess_id):
    grading_process = GradingProcess.objects.get(pk=gradingprocess_id)
    grading_assignments = GradingAssignment.objects.filter(grading_process=grading_process)
    assignment_items = AssignmentItem.objects.filter(assignment=grading_process.assignment)
    student_submissions = StudentSubmissionItem.objects.filter(assignment_item__in=assignment_items)
    grades_table = gradingtables.AssignmentGradesTable(student_submissions)
    grades_table.paginate(page=request.GET.get('page', 1), per_page=25)
    context = {
        'grading_process': grading_process,
        'grading_assignments': grading_assignments,
        'assignment_items': assignment_items,
        'grades_table': grades_table,
    }
    return render(request, 'instructor/gradingdetails.html', context)

# grading for a single item details view
def gradingitemdetails(request, gradingprocess_id, assignmentitem_id):
    grading_process = GradingProcess.objects.get(pk=gradingprocess_id)
    student_submissions = StudentSubmissionItem.objects.filter(assignment_item=assignmentitem_id)
    item_grades = StudentSubmissionItemGrade.objects.filter(student_submission_item__in=student_submissions)
    grades_table = gradingtables.StudentSubmissionItemGradeTable(item_grades)
    grades_table.paginate(page=request.GET.get('page', 1), per_page=25)
    assignment_item = AssignmentItem.objects.get(pk=assignmentitem_id)
    context = {
        'grading_process': grading_process,
        'assignment_item': assignment_item,
        'grades_table': grades_table,
    }
    return render(request, 'instructor/gradingitemdetails.html', context)

# create new gradingassignment
# form elements grading_process_id, assignment_item
def gradingitem(request):
    try:
        new_gradingassignment = GradingAssignment.objects.create(grading_process=GradingProcess.objects.get(id=request.POST['grading_process_id']), assignment_item=AssignmentItem.objects.get(id=request.POST['assignment_item']))
        new_gradingassignment.save()
    except:
        raise Http404("Error creating grading assignment")
    return HttpResponseRedirect(reverse('instructor:gradingdetails', args=(request.POST['grading_process_id'],)))


def gradingstart(request):
    """
    request contains gradingprocess_id
    for each gradingassignment, initialize and grade
    """
    grading_process_id = request.POST['grading_process_id']
    grading_process = GradingProcess.objects.get(pk=grading_process_id)
    grading_process.gradingstatusupdate('Initializing')
    grading_assignmentitem = GradingAssignmentSerializer(GradingAssignment.objects.filter(grading_process=grading_process), many=True)

    # get token to pass to API
    adminuser = User.objects.get(username='admin')
    token = Token.objects.get(user=adminuser.id)

    # make a post request to APIURL /gradingrunprocess/<grading_process_id>
    # with grading_assignmentitem as json
    # token.key in header
    callURL = APIURL+'grading/'+grading_process_id
    headers = {'apikey': token.key}
    print(json.dumps(grading_assignmentitem.data))
    print(headers)
    startGrading = requests.post(callURL, json=json.dumps(grading_assignmentitem.data), headers=headers)

    if startGrading.status_code != 200:
        grading_process.gradingstatusupdate('Error initializing grading service')

    return HttpResponseRedirect(reverse('instructor:gradingdetails', args=(request.POST['grading_process_id'],)))

webui/instructor/views/imports.py
import csv, io
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

from ..models import Student, StudentGroup


# imports a csv file with students for a specific group
def import_students_togroup(request):
    if request.method == 'POST':
        group_id = request.POST.get('group_id')
        group = StudentGroup.objects.get(id=group_id)
        csvfile = request.FILES['csvfile']
        if csvfile.name.endswith('.csv'):
            csvdata = csvfile.read().decode('utf-8')
            datastream = io.StringIO(csvdata)

            reader = csv.reader(datastream, delimiter=',', quotechar='"')
            student_list = []
            for row in reader:
                student = Student(
                    first_name = row[0],
                    last_name = row[1],
                    student_custom_id = row[2],
                    student_group = group
                )
                student_list.append(student)
            if len(student_list) > 0:
                Student.objects.bulk_create(student_list)
            return HttpResponseRedirect(reverse('instructor:studentgroupdetails', args=(group_id,)))
        else:
            return HttpResponse('Only csv files are supported')
    else:
        raise Http404

webui/instructor/templates/instructor/assignmentitem.html
{% extends "base.html" %}

{% load startswith %}

{% block title %}Assignment Item {{ assignment_item.item_name}}{% endblock %}
{% block tabname %}assignments{% endblock %}
{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'instructor:assignmentlist' %}">Assignments</a></li>
    <li class="breadcrumb-item"><a href="{% url 'instructor:assignment' %}/{{ assignment_item.assignment.id}}">{{ assignment_item.assignment.assignment_name}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Item {{ assignment_item.item_name}}</li>
{% endblock %}

{% block content %}

<!-- show general assignment info -->
<div class="row">
    <div class="col-md-6">
        <h2><i class="fas fa-list-ol"></i> {{ assignment_item.assignment.assignment_name}} Item: {{ assignment_item.item_name}}</h2>
        {% if assignment_item.item_type == 'QUERY' and assignment_item.item_solution %}
            Correct query: <a href="{{ MEDIA_URL }}{{ assignment_item.item_solution }}">{{ assignment_item.item_solution }}</a>
        {% endif %}
    </div>
<!-- form for editing assignment info -->
    <div class="col-md-6 pb-3">
        <div class="card"><div class="card-body">
        <h5 class="card-title">Edit assignment item</h5>
        <form action="{% url 'instructor:assignmentitemedit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <input type="hidden" name="assignment_item_id" value="{{ assignment_item.id }}">
                <div class="row">
                    <div class="col mb-3">
                        <div class="form-floating">
                            <input type="text" class="form-control" id="item_name" name="item_name"
                                value="{{ assignment_item.item_name }}">
                            <label for="item_name">Item Name</label>
                        </div>
                    </div>
                    <div class="mb-3" {% if assignment_item.item_type != 'QUERY' %}style="display:none;"{% endif %}>
                        <label for="item_code">Correct Query:</label>
                        <input type="file" id="item_code" name="item_code" accept="*" >
                    </div>
                    <div class="mb-3 float-end">
                        <button type="submit" class="btn btn-secondary btn-sm float-end" value="Update assignment environment">
                            Update Assignment Item <i class="fas fa-save"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
        </div></div>
    </div>
</div>

<!-- list of testing instances -->
<div class="row border-top pt-3">
    <div class="col-md-6">
        <h3><i class="fas fa-server"></i> Environment Instances</h3>
        <div class="card">
        <div class="card-body">
        <h5 class="card-title">Add environment for item grading</h5>
        <form action="{% url 'instructor:environmentinstance' %}" method="post" enctype="multipart/form-data">
            <input type="hidden" name="assignment_item_id" value="{{ assignment_item.id }}">
            {% csrf_token %}
            <div class="form-group">
                <div class="row">
                    <div class="col mb-3">
                        <div class="form-floating">
                            <input type="text" class="form-control" id="environment_name" name="environment_name" style="width:250px;" >
                            <label for="environment_name">Environment Name</label>
                        </div>
                    </div>
                    <div class="col mb-3">
                        <div class="form-floating">
                            <input type="number" class="form-control" id="points_possible" name="points_possible" style="width:250px;" value="100">
                            <label for="points_possible">Points</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col mb-3">
                        <label for="initial_code">Item-specific environment setup (optional):</label>
                        <input type="file" id="initial_code" name="initial_code" accept=".sql">
                    </div>
                    <div class="col pt-3 mb-3">
                        <button type="submit" class="btn btn-success float-end" value="Add item environment">
                            Add Item Environment <i class="fas fa-plus-square"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
        </div>
        </div>
    </div>
    <div class="col-md-6">
        {% if environment_instance %}
            {% for env_instance in environment_instance %}
            <div class="card mt-2">
                <div class="card-header bg-primary text-white" id="headingEI{{ env_instance.id }}">
                    <i class="fas fa-database"></i>
                    Instance: {{ env_instance.environment_name }}
                </div>

                <div class="card-body">
                    {% if env_instance.initial_code %}
                    <div class="row"><div class="col mb-6 pb-4">
                        Current specific setup script: <a href="{{ MEDIA_URL }}{{ env_instance.initial_code }}">{{ env_instance.initial_code }}</a>
                    </div></div>
                    {% endif %}
                    <form action="{% url 'instructor:environmentinstanceedit' %}" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="environment_instance_id" value="{{ env_instance.id }}">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="row">
                                <div class="col mb-3">
                                    <div class="form-floating">
                                        <input type="text" class="form-control" id="environment_name" name="environment_name" style="width:250px;" value="{{ env_instance.environment_name }}">
                                        <label for="environment_name">Environment Name</label>
                                    </div>
                                </div>
                                <div class="col mb-3">
                                    <div class="form-floating">
                                        <input type="number" class="form-control" id="points_possible" name="points_possible" style="width:250px;" value="{{ env_instance.points_possible }}">
                                        <label for="points_possible">Points</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col mb-3">
                                    <label for="initial_code">Environment instance setup (optional):</label>
                                    <input type="file" id="initial_code" name="initial_code" accept=".sql">
                                </div>
                                <div class="col pt-4 mb-3">
                                    <button type="submit" class="btn btn-secondary btn-sm float-end" value="Update environment">
                                        Update Environment <i class="fas fa-save"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="row">
                        {% if env_instance.has_datagen %}
                            <h6>Data Generation: {{ env_instance.datagen_status }}</h6>
                        {% else %}
                        <form action="{% url 'instructor:environmentinstancedatagen' %}" method="post">
                            <input type="hidden" name="environment_instance_id" value="{{ env_instance.id }}">
                            <input type="hidden" name="assignment_item_id" value="{{ assignment_item.id }}">
                            <input type="hidden" name="initial_code" value="{{ env_instance.initial_code }}">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="row">
                                    <div class="col mb-2">
                                        <h6>Auto Data Generation</h6>
                                    </div>
                                    <div class="col mb-2">
                                        <div class="form-floating">
                                            <input type="number" class="form-control" id="row_count" name="row_count" style="width:120px;" value="500">
                                            <label for="row_count">Row Count</label>
                                        </div>
                                    </div>
                                    <div class="col mb-2">
                                        {{ env_instance.datagen_status }}
                                        <button type="submit" class="btn btn-warning btn-sm float-end mt-3" value="Start Data Generation">
                                            Start Data Generation <i class="fas fa-file-code"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        {% endif %}
                    </div>
                </div>
                {% if env_instance.allfiles %}
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <h6>Instance Files:</h6>
                    </li>
                    {% for file in env_instance.allfiles %}
                    <li class="list-group-item">
                        {% if file|startswith:'datagen/' %}
                            <i class="fas fa-file-code"></i>
                        {% else %}
                            <i class="fas fa-file-alt"></i>
                        {% endif %}
                        <a href="{{ MEDIA_URL }}itemenv_{{ env_instance.id }}/datagen/{{ file }}">{{ file }}</a></li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            {% endfor %}
        {% else %}
        <p>No environment instances for grading this item found.</p>
        {% endif %}

    </div>
</div>




{% endblock %}

webui/instructor/templates/instructor/studentgroups.html
{% extends "base.html" %}

{% block title %}Student Groups{% endblock %}

{% block content %}

<!-- a form to create a new studentgroup -->
<form action="{% url 'instructor:studentgroup' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="group_name">Group Name</label>
        <input type="text" class="form-control" id="group_name" name="group_name" placeholder="Enter group name">
    </div>
    <input type="submit" class="btn btn-primary" value="Create Group">
</form>

<!-- list of groups -->
{% if active_groups %}
    <ul>
    {% for studentgroup in active_groups  %}
        <li><i class="fas fa-camera"></i> <a href="instructor/studentgroup/{{ studentgroup.id }}/">{{ studentgroup.group_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No students entered.</p>
{% endif %}


{% endblock %}

webui/instructor/templates/instructor/studentsubmission.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title %}Assignment  submission by {{ submission.student.first_name }} {{ submission.student.last_name }}{% endblock %}
{% block tabname %}students{% endblock %}
{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'instructor:studentlist' %}">Students</a></li>
    <li class="breadcrumb-item"><a href="{% url 'instructor:studentdetails' student_id=1 %}">{{ submission.student.first_name }} {{ submission.student.last_name }} ({{ submission.student.student_custom_id }})</a></li>
    <li class="breadcrumb-item active" aria-current="page">Submission: {{ submission.assignment.assignment_name }}</li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <h2><i class="fas fa-book"></i> {{ submission.assignment.assignment_name}} by {{ submission.student.first_name }} {{ submission.student.last_name }} ({{ submission.student.student_custom_id }})</h2>
    </div>
</div>

<div class="row">
    <!-- list of student submissions -->
    <div class="col-md-6 mt-3">
        <h5><i class="fas fa-list-ol"></i> Assignment Item Submissions</h5>
        {% if assignment_items %}
        <ul>
            {% for assignment_item in assignment_items %}
            <li class="list-group-item">{{ assignment_item.item_number }}: {{ assignment_item.item_name }} 
                {% for item in submission_items %}
                    {% if item.assignment_item_id == assignment_item.id %}
                        <i class="fas fa-file-code"></i> <a href="{{ MEDIA_URL }}{{ item.submission_file }}">{{ item.submission_file }} </a>
                        <br/> {{ item.grading_log }}
                    </li>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>



<!-- grade details -->
<div class="row">
    <div class="col-md-12">
        <h5>Grades</h5>
        {% render_table grade_table %}
    </div>
</div>




{% endblock %}